export const COLOR = {
    PRIMARY_COLOR:"#03A9F4",
    ACCENT_COLOR: "#FF4081",
    PRIMARY_TEXT: "#212121",
    SECONDARY_TEXT: "#757575",
    DIVIDER_COLOR: "#BDBDBD",
    DARK_PRIMARY_COLOR: "#0288D1",
    LIGHT_PRIMARY_COLOR: "#B3E5FC",
    TEXT_ICONS_COLOR: "#FFFFFF",
}